### ISSUE TITLE
even when '/passport' dir is created on the SD card, application does not work as expected

### ISSUE THREAD

**Issue by lwiechec** [strukturart/passport#2]
thanks for the app like that - I was looking for something that could help me reduce printing out pages with qr codes!

I am sure I am doing something ; when I start the app, it says: the folder '/passport' does not exist, please create the dir or the dir is empty.

I made '/passport' dir on the SD Card; I even put sth there - created 'images' directory...

**Comment by strukturart** [comment]
try adding a .png or .jpg file to the directory

**Comment by strukturart** [comment]
any news ?
