### ISSUE TITLE
bottom and right border to big

### ISSUE THREAD

**Issue by vlycop** [strukturart/passport#3]
Hello. Thanks a lot for this 
I think there is a math error in the qrcode picture generators.
Specifically the part that generate the white border around it.

I've noticed that while the top and left border look to always be the same size, the bottom and right border grow based on the size of the qrcode.

This issue have become apparent when scanning European covid certificates, which are really big.
Almost 1/5 of the screen is white. 

I obviously can't send you this one, but here is an example of a small increase.

It doesn't look to be linear to the total size.

![Lorem1](https://user-images.githubusercontent.com/17001679/133002723-78ca0226-a95f-47f4-be0a-20a8fc9f8fbd.png)

**Comment by strukturart** [comment]
you can try the app again to test whether my changes have improved a bit

**Comment by Vaarlion** [comment]
sadly no, the botom and right side are still the same, but the top and left are now 1 px only
![tfrt](https://user-images.githubusercontent.com/59558433/133260734-c38c5571-c51f-4afe-80b2-ffa8beab15d4.png)

**Comment by vlycop** [comment]
Sadly no :(
The bottom and right border look the same, while the left and top one now is only 1 px wide
![tfrt](https://user-images.githubusercontent.com/17001679/133261182-4ed1c1c6-8988-4fba-8270-99933ad1bee9.png)

**Comment by strukturart** [comment]
do you have any programming skills? if so, can you please try out the values?

https://github.com/strukturart/passport/blob/71e1d45ef5d6b654b15c219c7bbdaa6774672190/application/index.js#L169

**Comment by vlycop** [comment]
I'm sorry, what do you mean by "try out" ?
This value '800' is already what is setted on the app right now
Do you want me to play with it and see what's look better?

I feel like changing a size value won't solve what look like a padding issue.

I have little to no skilz in js, and in general i'm limited to small scripting. But i'm willing to help where i can :D
Please clarify what you wish me to do :+1:

**Comment by strukturart** [comment]
I don't know exactly where I can influence the behavior of the size of the generated qr code. i can change the image size and padding, but i need your help to test it. It looks good for me now, but I can't scan a covid certificate with my phone because I don't have a printout and the qr code on the screen is too complex.

**Comment by strukturart** [comment]
@vlycop did you test the new version?

**Comment by vlycop** [comment]
Very sorry, am in not in a place with access to a computer ...
Please give me until Tuesday
